module Main where

import Html
import Markdown
import People

generatePeople :: FilePath -> IO HTML
generatePeople file = do
  input <- readPeopleFile file
  let msp = groupMSP (people input)
  concat <$> sequence
        [ pure $ h2 "People"
        , translateMarkdown (preamble input)
        , peopleToHTML "Academic Staff" (academic msp)
        , peopleToHTML "Research Staff" (research msp)
        , peopleToHTML "PhD Students" (student msp)
        , peopleToHTML "Alumni" (alumni msp)
        ]

main :: IO ()
main = do
  people <- generatePeople "people.yaml"
  let header = "### default.html(section.people=current)\n<!-- DO NOT EDIT THIS FILE DIRECTLY — EDIT people.yaml AND RUN GeneratePeople.hs INSTEAD -->"
  writeFile "people.html" (header ++ people)
